// ============================================================
// E2E: full order form flow against the live Supabase project.
// Drives the real UI in headless Chrome:
//   home -> product page -> dynamic options -> validation error
//   -> filled submit -> DB order -> WhatsApp URL -> success state
// Option-agnostic: fills every input whose id starts with "option-"
// (the OrderForm generates those ids from the DB option definitions).
// Usage: node scripts/e2e_order_form.mjs
// ============================================================
import puppeteer from "puppeteer-core";

const CHROME = "C:/Program Files/Google/Chrome/Application/chrome.exe";
const BASE = "http://localhost:3001";
const SLUG = "meuble-tv-flottant-noyer"; // seed 0005 product
const MARKER = "E2E-TEST Client";

const consoleErrors = [];
const failedRequests = [];

function out(json) {
  console.log(JSON.stringify(json, null, 2));
}

const browser = await puppeteer.launch({
  executablePath: CHROME,
  headless: true,
  args: ["--no-sandbox", "--disable-gpu", "--disable-dev-shm-usage"],
});
try {
  const page = await browser.newPage();
  await page.setViewport({ width: 1366, height: 900 });

  page.on("console", (m) => {
    if (m.type() === "error") consoleErrors.push(m.text());
  });
  page.on("pageerror", (e) => consoleErrors.push(`pageerror: ${e.message}`));
  page.on("response", (r) => {
    if (r.status() >= 400) failedRequests.push(`${r.status()} ${r.url()}`);
  });

  // --- 1. Home renders (SSR data from live Supabase) ---
  await page.goto(BASE + "/", { waitUntil: "networkidle2", timeout: 45000 });
  const homeText = await page.evaluate(() => document.body.innerText);
  const homeOk = homeText.includes("Votre intérieur") && homeText.includes("Nos catégories");

  // --- 2. Product page with dynamic options ---
  let resp = await page.goto(`${BASE}/products/${SLUG}`, {
    waitUntil: "networkidle2",
    timeout: 45000,
  });
  let productOk = resp.status() === 200;
  let bodyText = productOk ? await page.evaluate(() => document.body.innerText) : "";
  if (!productOk || bodyText.includes("Produit introuvable")) {
    // Fallback: first product link on /products
    await page.goto(BASE + "/products", { waitUntil: "networkidle2", timeout: 45000 });
    const href = await page.evaluate(() => {
      const a = [...document.querySelectorAll('a[href^="/products/"]')].find(
        (x) => x.getAttribute("href") !== "/products"
      );
      return a ? a.getAttribute("href") : null;
    });
    if (!href) {
      out({ fatal: "no product link found on /products", consoleErrors, failedRequests });
      process.exit(1);
    }
    resp = await page.goto(BASE + href, { waitUntil: "networkidle2", timeout: 45000 });
    productOk = resp.status() === 200;
    bodyText = await page.evaluate(() => document.body.innerText);
    productOk = productOk && !bodyText.includes("Produit introuvable");
  }

  const productName = await page.$eval("h1", (h) => h.textContent.trim());

  // Dynamic option inputs generated by OrderForm carry ids "option-<uuid>".
  const optionFields = await page.$$eval("[id^='option-']", (els) =>
    els.map((el) => ({
      id: el.id,
      tag: el.tagName.toLowerCase(),
      type: el.type ?? null,
    }))
  );
  const hasForm =
    optionFields.length > 0 &&
    (await page.$("#customer_name")) !== null &&
    (await page.$("#customer_phone")) !== null &&
    (await page.$("#customer_city")) !== null;

  // --- 3. Client-side validation blocks an incomplete submit ---
  await page.type("#customer_name", MARKER);
  await page.type("#customer_phone", "+212 611 223 344");
  await page.type("#customer_city", "Casablanca");
  await page.click('button[type="submit"]');
  await page
    .waitForFunction(() => document.body.innerText.includes("requis"), { timeout: 8000 })
    .catch(() => {});
  const validationText = await page.evaluate(() => document.body.innerText);
  const validationBlocked =
    validationText.includes("requis") &&
    !validationText.includes("Votre demande a été enregistrée");

  // --- 4. Fill every dynamic option input ---
  for (const f of optionFields) {
    const sel = `#${f.id}`;
    if (f.tag === "select") {
      const value = await page.$eval(sel, (s) => s.options[1]?.value ?? "");
      if (value) await page.select(sel, value);
    } else if (f.type === "number") {
      await page.click(sel, { clickCount: 3 });
      await page.type(sel, "180");
    } else if (f.tag === "textarea") {
      await page.type(sel, "Test E2E");
    } else {
      await page.type(sel, "Test E2E");
    }
  }
  await page.type("#customer_note", "Test E2E automatisé — à ignorer.");

  // What we actually set (label -> value), to assert against the WA message.
  const filled = [];
  for (const f of optionFields) {
    const label = await page.$eval(
      `label[for='${f.id}']`,
      (l) => l.textContent.trim().replace(/\*$/, "").trim()
    );
    const value = await page.$eval(`#${f.id}`, (el) => el.value);
    if (value) filled.push({ label, value });
  }

  // --- 5. Capture the WhatsApp URL (stub window.open) and submit ---
  await page.evaluate(() => {
    window.__waUrl = null;
    window.open = (u) => {
      window.__waUrl = u;
      return null;
    };
  });

  await page.click('button[type="submit"]');

  const submitted = await page
    .waitForFunction(
      () =>
        document.body.innerText.includes("Votre demande a été enregistrée") ||
        document.body.innerText.includes("Une erreur est survenue") ||
        (window.__waUrl && document.body.innerText.includes("introuvable")),
      { timeout: 25000 }
    )
    .then(() => true)
    .catch(() => false);

  const successShown = await page.evaluate(() =>
    document.body.innerText.includes("Votre demande a été enregistrée")
  );
  const errorShown = await page.evaluate(() =>
    document.body.innerText.includes("Une erreur est survenue")
  );
  const waUrl = await page.evaluate(() => window.__waUrl);

  let waChecks = null;
  if (waUrl) {
    const decoded = decodeURIComponent(waUrl);
    waChecks = {
      isWaMe: waUrl.startsWith("https://wa.me/"),
      phoneDigits: waUrl.match(/wa\.me\/(\d+)/)?.[1]?.length ?? 0,
      hasProduct: decoded.includes(productName),
      optionsInMessage: filled.map((p) => ({
        ...p,
        inMessage: decoded.includes(`${p.label} : ${p.value}`),
      })),
      hasCustomer: decoded.includes(MARKER) && decoded.includes("Casablanca"),
    };
  }

  out({
    productPage: { ok: productOk, productName },
    dynamicOptions: { hasForm, optionCount: optionFields.length },
    validationBlockedEmptySubmit: validationBlocked,
    submitted,
    successShown,
    errorShown,
    whatsapp: waChecks,
    waUrl,
    consoleErrors,
    failedRequests,
    homeOk,
  });
} finally {
  await browser.close();
}
